{
    "name": "libcusolver",
    "ecosystem": "pypi",
    "campaign": "2025-10-bugdotexe",
    "affected_versions": [
        "2.3.2",
        "11.4.1.48"
    ],
    "campaign_assigned_at": "2025-10-29T22:06:04.026253+00:00",
    "campaign_data_modified_at": "2025-10-30T07:21:28.650293+00:00"
}